import { Children } from '@/components/Childres';
import { StoreProviders } from '@/redux/provider';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'], preload: true });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <StoreProviders>
            <Children>
                <html lang="en">
                    <body className={inter.className}>{children}</body>
                </html>
            </Children>
        </StoreProviders>
    );
}
